### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-74min#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by DwayneArmster** [comment]
I have successfully replaced the image, and named the updated image as the one replaced "placeholder.png"

**Comment by DwayneArmster** [comment]
Here is a screenshot of the update as 
<img width="1009" alt="bugfix" src="https://user-images.githubusercontent.com/54452726/195130847-a724b32a-6c6a-4244-9f39-dfd104c06815.png">
